### ISSUE TITLE
org.openqa.selenium.WebDriverException: json: cannot unmarshal string into Go struct field Caps.sessionTimeout of type uint32

### ISSUE THREAD

**Issue by YogeshMahajan1903** [aerokube/images#134]
Observed with Centos-7, with Selenium - 3.11 & Selenoid -1.8.2

`			FirefoxOptions firefoxOption = new FirefoxOptions();
			firefoxOption.setAcceptInsecureCerts(true);
			firefoxOption.setHeadless(false);
			firefoxOption.addArguments("-foreground");
                        firefoxOption.setCapability("version", version);
			firefoxOption.setCapability("enableVNC", true);
			firefoxOption.setCapability("enableVideo", true);
			firefoxOption.setCapability("videoName",videoName+".mp4");
			firefoxOption.setCapability("logName",videoName+".log");
			firefoxOption.setCapability("name",videoName);
			firefoxOption.setCapability("platform", Platform.LINUX);
			firefoxOption.setCapability("resolve_ip", false);
			firefoxOption.setCapability("sessionTimeout", "60s");`

When launched with above configuration, Exception thrown - org.openqa.selenium.WebDriverException: json: cannot unmarshal string into Go struct field Caps.sessionTimeout of type uint32.

**Comment by Asgoret** [comment]
Still here :)

**Comment by vania-pooh** [comment]
@Asgoret we know.
