### ISSUE TITLE
Android 8.1 container start very slowly

### ISSUE THREAD

**Issue by sasha943** [aerokube/images#172]
I build two images, **Android 6.0** and **Android 8.1**. 
Diff only in sdk and chromedrivers versions
Started only 1 container, run several times. Always Android 8.1 much more slowly than Android 6.0

Android 6.0 container init time:
`Start init container: Mon Jul 08 2019 10:33:27
io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: OSS
Finish init container: Mon Jul 08 2019 10:34:22`

Android 8.1
`Start init container: Mon Jul 08 2019 10:29:07
io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: OSS
Finish init container: Mon Jul 08 2019 10:31:24`

_Maybe exists some params or args for descrease init driver time..._

**Comment by vania-pooh** [comment]
@sasha943 we noticed that 8.1 is slightly bigger and slower and has an issue when running emulator with `-no-window` flag.

**Comment by sasha943** [comment]
@vania-pooh Thanks for answer

**Comment by sasha943** [comment]
@vania-pooh any estimates or future plan for this?

**Comment by vania-pooh** [comment]
@sasha943 not sure, this could be an issue in Android emulator and may require some action from Google side.
