### ISSUE TITLE
Android: The desired capabilities must include either an app, appPackage or browserName

### ISSUE THREAD

**Issue by mikk150** [aerokube/images#185]
How to tell to Appium that I require Chrome browser?

**Comment by vania-pooh** [comment]
@mikk150 just use `browserName = chrome`.

**Comment by mikk150** [comment]
but I have to use `browserName = android` in order for it to give me android

**Comment by vania-pooh** [comment]
@mikk150 then use `deviceName = android`.

**Comment by mikk150** [comment]
> @mikk150 then use `deviceName = android`.

@vania-pooh and then we are at square one

**Comment by mikk150** [comment]
do I have to say in browsers.json that chrome image is android?

this part is really badly documented...

**Comment by vania-pooh** [comment]
@mikk150 you don't have to use `deviceName = android` in case of Chrome Mobile. Should have the following capabilities:
```
browserName = chrome
version = mobile-75.0
```
And you should have the same browser name and version in `browsers.json`.

**Comment by czenczakm** [comment]
I have the same issue. I'm trying to run tests in selenoid/android:8.1 
so in browsers.json I added: 
```
"android": {
  "default": "8.1",
  "versions": {
    "8.1": {
      "image": "selenoid/android:8.1",
      "port": "4444",
      "tmpfs": {"/tmp":"size=512m"}
    }
  }
}
```

and trying to start it by setting capabilities: 
```
desiredCapabilities.setBrowserName("android");
desiredCapabilities.setVersion("8.1");
```

in selenoid/android:8.1 container I got error: 
```
[AndroidDriver] Error: The desired capabilities must include either an app, appPackage or browserName
```

**Comment by aandryashin** [comment]
Try to change android to chrome and version to mobile-77.0 in
browsers.json, image should remain the same...

ср, 23 окт. 2019 г., 11:38 czenczakm <notifications@github.com>:

**Comment by vania-pooh** [comment]
@czenczakm These images are used for testing mobile applications in Android emulator and logically you have to specify which application to test. This is done via `app` capability. E.g. https://github.com/aerokube/demo-tests/blob/master/src/test/java/com/aerokube/selenoid/AndroidRemoteApkTest.java To work with Chrome Mobile use `selenoid/chrome:mobile-77.0` image.

**Comment by mikk150** [comment]
> selenoid/chrome:mobile-77.0

Please, try to download `selenoid/chrome:mobile-77.0` image, you will see that it fails miserably because those images do not exist

**Comment by vania-pooh** [comment]
@mikk150 did not build yet. Older versions exist.

**Comment by mikk150** [comment]
> @mikk150 did not build yet. Older versions exist.

https://hub.docker.com/r/selenoid/chrome/tags?page=1&name=mobile

I see no tags here... if I am not mistaken they should be here

**Comment by vania-pooh** [comment]
https://hub.docker.com/r/selenoid/chrome-mobile/tags

**Comment by DimqBBSQO** [comment]
> @vania-pooh 

Is it possible to make the selenoid/android image also have google chrome along with the app?

**Comment by vania-pooh** [comment]
@DimqBBSQO `selenoid/android` это по определению образ без Хрома. Вы всегда можете собрать себе такой образ самостоятельно, используя наши скрипты.
