### ISSUE TITLE
Need ability to upload files to clipboard

### ISSUE THREAD

**Issue by dtsvirkun** [aerokube/images#186]
I didnt find working soulution how it can be done with files. It works fine with text, but not with binary files, I was trying to upload  with:
```
RestAssured.given().log().all()
                .when()
                .multiPart(file)
                .post(url)
                .then();
```
But did not have succes to paste file to input field

**Comment by NikolasInjoglou** [comment]
Hello, any chance to implement this please?

**Comment by vania-pooh** [comment]
@NikolasInjoglou currently we only have image upload to clipboard in Moon already implemented. https://aerokube.com/moon/latest/#clipboard
