### ISSUE TITLE
Containers spun up from Chrome image have an invalid timezone being set and no locale set

### ISSUE THREAD

**Issue by aditki** [aerokube/images#190]
Ex: Wed Nov  6 17:46:05 Local 2019

Shouldn't it be a valid Timezone instead of Local. 

And the Browser containers don't have locale setup.

``` 
$ docker exec -it f09fa2077c56 locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
This is causing Javascript errors..

**Comment by vania-pooh** [comment]
@aditki timezone is set via `TZ` variable. E.g. in Selenoid you can also set it with capability `timeZone`: https://aerokube.com/selenoid/latest/#_per_session_time_zone_timezone

**Comment by aditki** [comment]
@vania-pooh The documentation says its for setting capabilities for individual tests. That shouldn't mean that there will be no default locale will be set.

**Comment by vania-pooh** [comment]
@aditki for every browser version you can also set respective environment variable in `browsers.json`:
```
{
    "firefox": {                                     
      "default": "70.0",                             
      "versions": {                                  
        "70.0": {                                    
          "image": "selenoid/firefox:70.0",          
          "port": "4444",                            
          "env" : ["TZ=Europe/Moscow", "LC_ALL=en.en_US"]
        }
    }
}
```
