### ISSUE TITLE
Android Emulators fail on clicking the side buttons to control the emulator

### ISSUE THREAD

**Issue by sagarwadhwa1** [aerokube/images#219]
As soon as I click on the side buttons [buttons.jpg](https://i.ibb.co/pR13z7F/Screenshot-2020-01-20-at-11-56-13-AM.png), the emulator fails and closes. This causes problems as we're unable to set options when manually controlling the emulator.

**Comment by vania-pooh** [comment]
Probably we have to add some missing libraries or window manager.

**Comment by sagarwadhwa1** [comment]
@vania-pooh Here are the associated logs:

> [66:66:0120/132631.829538:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
> 2020-01-20 13:26:31:956 - [debug] [UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
> 2020-01-20 13:26:31:957 - [Logcat] Logcat terminated with code 0, signal null

**Comment by vania-pooh** [comment]
@sagarwadhwa1 now we added Fluxbox and rebuilt Android images and it works.
