### ISSUE TITLE
[chrome] Chrome failed to start: exited abnormally

### ISSUE THREAD

**Issue by sbengo** [aerokube/images#220]
Hello,

First of all, thanks for this awesome repository and awesome images. I'm not sure it's the right repository, sorry for any inconvenience.

We are currrently using selenoid images (from dockerhub) to launch as remote webdriver, navigations based on RobotFramework and scheduled/executed by Drone CI:

```
selenoid/chrome:78
```

We are setting `chromedriver` with the following params:

```
SeleniumLibrary: 4.1.0
RobotFramework: 3.1.1

Chromedriver params: --no-sandbox --ignore-certificate-errors prefs: { intl.accept_languages : <lang defined by the user>} 
```

The docker service is being configured with the following shm size and it has enough resources: (more than 20GB and 90% of idle CPU)

```
shm_size: 2g
```

As we have seen, with an avg 1 of 100 executions, it seems that chrome is unable to start due to the following error: `WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally`

Do you have idea why chrome is unable to start?

- Roboframework log:
```
WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
--
34 | (unknown error: DevToolsActivePort file doesn't exist)
35 | (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

- Selenoid/chrome docker logs:

```
[1580183028.574][INFO]: Launching chrome: /usr/bin/google-chrome --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-blink-features=ShadowDOMV0 --enable-logging --force-fieldtrials --ignore-certificate-errors --load-extension=/tmp/.com.google.Chrome.lPlaeW/internal --log-level=0 --no-first-run --no-sandbox --password-store=basic --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.com.google.Chrome.KcOKeo data:,
--
110 | [81:113:0128/034348.980746:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
111 | Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
112 | [0128/034349.028864:ERROR:nacl_helper_linux.cc(311)] NaCl helper process running without a sandbox!
113 | Most likely you need to configure your SUID sandbox correctly
114 | [1580183029.055][INFO]: [4d1a81e030f1ad6c6cc871970aee9af8] RESPONSE InitSession ERROR unknown error: Chrome failed to start: exited abnormally
115 | (unknown error: DevToolsActivePort file doesn't exist)
116 | (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
117 | [1580183029.055][DEBUG]: Log type 'driver' lost 0 entries on destruction
118 | [1580183029.055][DEBUG]: Log type 'browser' lost 0 entries on destruction
119 | [132:132:0128/034349.265681:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
```

Thanks,
Regards

**Comment by vania-pooh** [comment]
@sbengo could you try whether this issue is reproducing with other Chrome versions? It seems that Chrome 78 is not so stable.

**Comment by sbengo** [comment]
Thanks for the asnwer @vania-pooh !
Sorry for the question, but, what version do you recommend?

Thanks,
Greetings!

**Comment by vania-pooh** [comment]
@sbengo e.g. 77.0.

**Comment by sbengo** [comment]
Thanks for quick answer @vania-pooh , will try to test `selenoid/chrome:77` image during the next week and will give you some feedback!

Thanks,
Regards!

**Comment by FJG-Elelog** [comment]
I'm also getting this error but it is sort of random. I'm using the docker/standalone chromedriver and it works just fine up until a certain point.
I started debugging and everything was fine. Second time I tried to debug, it crashed (no changes in the code tho).
Any ideas?
Could be the multithreading? (The versions I used are the ones in the container: https://hub.docker.com/r/selenium/standalone-chrome)
As I'm kinda new to this, I'm not sure if it is possible to change the versions within the container.

Thank you very much in advance, 
Best regards

**Comment by vania-pooh** [comment]
@FJG-Elelog could be e.g. a bug in Chrome. For example in some recent version of Chrome it was crashing if a big webp picture was present on the page. Updating to latest version seems to fix this.

**Comment by FJG-Elelog** [comment]
I'm not really sure, I've being checking out and standalone-chrome uses the latest versions by default (not sure tho, as I'm really new to this). I've come across another error tho:
The code was executing just fine during hours and by the end of the day, without changing a thing crashes with this message:

Message: No active session with ID 

Again looked for it and once more versioning issues... I don't know how can I have versioning issues when I'm using the selenium container

**Comment by vania-pooh** [comment]
@FJG-Elelog we don't have any relation to `selenium/standalone-chrome` source code.

**Comment by FJG-Elelog** [comment]
I'm sorry, thought it might contribute/add to the issue :s
