### ISSUE TITLE
Ability to read root CA file from the volume

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/images#225]
Add respective commands to the entrypoint.

**Comment by v3g3t4x** [comment]
Hi, which was the issue resolved?
Belfiore of this fix what happen?
I have a strange behavior with a Tls1.2 site with client authentication with pfx file.
Works on chrome and firefox in windows, works on firefox into selenoid docker container but fail auth cert handshake with chrome into selenoid  chrome standalone 80.

**Comment by vania-pooh** [comment]
@v3g3t4x this is not yet fixed.

**Comment by anton85bk** [comment]
My vote+.
This would be a really useful thing and can get rid some users from a great headache.

**Comment by vania-pooh** [comment]
@anton85bk it works in Chrome already, but not yet for Firefox.

**Comment by dvyakimov** [comment]
That would be helpful!

**Comment by vania-pooh** [comment]
Fixed in Opera, Chrome, Edge, Firefox.

**Comment by patsevanton** [comment]
Great!
