### ISSUE TITLE
Create a Chromium Browser Image

### ISSUE THREAD

**Issue by Expoverse** [aerokube/images#228]
<img src="https://upload.wikimedia.org/wikipedia/commons/f/f3/Chromium_Material_Icon.png" width="48">

https://www.chromium.org/
https://github.com/chromium/chromium

<b>Browsers based on Open Source Chromium Browser</b>
https://en.wikipedia.org/wiki/Chromium_(web_browser)#Browsers_based_on_Chromium

= 

| Chrome | New Edge | Opera | Yandex | Samsung | Amazon Silk | Avast Secure Browser |More
| :-------------: |:-------------:| :-------------: | :-------------: | :-------------: | :-------------: | :-------------: | :-------------: |
| <img src="https://1000logos.net/wp-content/uploads/2017/08/Chrome-Logo.png" width="48">      | <img src="https://upload.wikimedia.org/wikipedia/en/thumb/9/98/Microsoft_Edge_logo_%282019%29.svg/1200px-Microsoft_Edge_logo_%282019%29.svg.png" width="38"> | <img src="https://www-static.operacdn.com/static-heap/75/759b5d5a74e1be5fdfd0fd1fed338c9d1c6cbb33/opera-152.png" width="48"> | <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Yandex.Browser_icon.svg/220px-Yandex.Browser_icon.svg.png" width="48"> | <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Samsung_Internet_logo.svg/150px-Samsung_Internet_logo.svg.png" width="38"> | <img src="https://upload.wikimedia.org/wikipedia/en/e/ef/Amazon_Silk_browser_icon.png" width="38"> | <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Avast_Secure_Browser.png/64px-Avast_Secure_Browser.png" width="38">  | 14+

65% of Internet Users use Chromium base browsers
https://www.w3counter.com/globalstats.php
https://en.wikipedia.org/wiki/Usage_share_of_web_browsers
https://www.statista.com/statistics/544400/market-share-of-internet-browsers-desktop/
<br>
This is the base open source browser in which many browsers are built upon. Just makes sense to test on a latest stable chromium image. Creating this should be easy. A website passing on chromium will pass on 21+ other active browsers.
<br>
<b>Tasks:</b>
1) Create image and add to repository.
2) Update documentation to include added image. 
<br>
<b>Side Comments / Thoughts:</b><br><br>
"Chromium's user interface is minimalist. Google sought to make the browser "feel lightweight (cognitively and physically) and fast." - <i>Chromium Developer Documentation</i><br><br>
I think perhaps testing on a chromium image would reduce browser server CPU consumption vs testing on a heavier chrome image since this omits all of googles inclusions. I will share my results here once access to image has been made.<br><br>
The fact alone that it targets many browsers at their core really makes this image appealing.

<br>
<br>

**Comment by vania-pooh** [comment]
@Expoverse any idea how to download Debian package for exact Chromium version?

**Comment by Expoverse** [comment]
<h4>Google Provides Chromium Snapshots Archive</h4>

Using appspot, query the exact version to get the commit. 
`https://omahaproxy.appspot.com/deps.json?version=80.0.3987.132`

This would return parsable json 
<pre>
{
"chromium_version": "80.0.3987.132", 
"skia_commit": "ac0e515499dbbfd8de62ed1eb7b5d0f2ad6a7679", 
"chromium_base_position": "722274", 
"v8_version": "8.0.426.26", 
"v8_commit": "2ad0a63d4a25377f3dc5eae52ef87505518867e8", 
"chromium_branch": "3987", 
"v8_position": "53",
"chromium_base_commit": 
"c4e8da9871cc266be74481e212f3a5252972509d", 
"chromium_commit": "aef8d0d95ba78d006e1ee65dff907bd824c7389b"
}
</pre>

In this case it returns a <b>"chromium_base_position"</b> of "722274".
<br>
<h4>Google's Archived Chromium Snapshots</h4>


Download the files using Machine Hardware and Base Position <i>?prefix=Linux_x64/722794/</i>
722794 doesn't return anything. Sometimes there is not a direct match so decrement the commit number until you find one. 

For example decrementing 5 times to 722269 provides the nearest snapshots.

`https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/722269/`

This provides
<pre>
REVISIONS
chrome-linux.zip
chromedriver_linux64.zip
content-shell.zip
devtools-frontend.zip
headless-shell.zip
pnacl.zip
</pre>

To download a specific files with code:  
`https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F722269%2Fchrome-linux.zip?alt=media
`<br>
Just change the filename to get the rest. Note the `Linux_x64` as hardware, `722269` as position and `chrome-linux.zip` as file in order to change the download link variables. 
<br><br>

<b>Notes:</b> This is the home directory for Chromium snapshots<br>
`https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html`
