### ISSUE TITLE
Not all logs are being written to container's stdout/stderr

### ISSUE THREAD

**Issue by rsotnychenko** [aerokube/images#229]
Hello,

I have had an issue with running Selenoid locally and spent a some time debuging it.
There weren't any useful logs from neither Selenoid container nor browser's. 

When I finally found this line:
https://github.com/aerokube/selenoid-images/blob/86ca73b0f0be7d86fd7007cd274660d28eb7c68d/selenium/chrome/entrypoint.sh#L47
I removed the redirect to `/dev/null` and an error message came up, giving me the exact reason what is wrong...

I wasn't expecting this behaviour from a container (especially a short-lived one) and therefore I'm wondering what is the reasoning behind placing that redirect?

**Comment by vania-pooh** [comment]
@rsotnychenko just because in the majority of cases these logs are useless. We mainly expect Chromedriver logs to be output to stdout.
