### ISSUE TITLE
Appium deprecated capability related command line switches

### ISSUE THREAD

**Issue by alfeg** [aerokube/images#246]
Appium switches `--device-name`, `--platform-name` and `--chromedriver-port` is deprecated if favor of `--default-capabilities`
https://github.com/aerokube/selenoid-images/blob/a043bca6f72ae48ed2d48caea9367889c401198e/selenium/android/entrypoint.sh#L73

According to Appium sources and documentation, following switches should be replaced with thise capabilities:
- `--chromedriver-port` => `"chromedriverPort"` https://github.com/appium/appium/blob/7e344367d61ec49db6104bdd4e473d8a2582f7c8/lib/parser.js#L785
- `--device-name` => `"deviceName"` https://github.com/appium/appium/blob/7e344367d61ec49db6104bdd4e473d8a2582f7c8/lib/parser.js#L465
- `--platform-name` => `"platformName"` https://github.com/appium/appium/blob/7e344367d61ec49db6104bdd4e473d8a2582f7c8/lib/parser.js#L438

**Comment by vania-pooh** [comment]
@alfeg PRs are welcome. :)

**Comment by alfeg** [comment]
@vania-pooh I would be glad to do it, but for now I have nowhere to test changes.
