### ISSUE TITLE
Beta and dev images for Chrome and Firefox

### ISSUE THREAD

**Issue by bonigarcia** [aerokube/images#26]
It would be great if any time you release a new image tag for Chrome y Firefox, you also release another image with the next beta and dev versions for these browsers. I mean `selenoid/chrome:beta`, `selenoid/chrome:dev`, `selenoid/chrome:beta`,  `selenoid/chrome:dev`, etc. What do you think?

**Comment by vania-pooh** [comment]
@bonigarcia yes, I know about such requirement. Currently it seems too much work for me. Also there are different development versions: `canary`, `alpha`, etc. Which one should be selected?

**Comment by bonigarcia** [comment]
@vania-pooh I think the most convenient would be the beta version of Chrome and Firefox. With those images in Docker we can test the next version of the most used browsers, which in my opinion would be very useful for the test community.

**Comment by vania-pooh** [comment]
@bonigarcia ok. Related to #25. :)

**Comment by kolodiy** [comment]
@vania-pooh this will be really useful for us as well, in the scope of moon usage. Can you please add such images soon?

**Comment by vania-pooh** [comment]
@kolodiy I will think about it. I would like to finish stabilizing features like Chrome Devtools and waiting for window manager first.

**Comment by ruescar** [comment]
At Twilio, we are working on developing this on our fork https://github.com/twilio/selenoid-images
Let us know if you have some feedback or some branch with similar work.

**Comment by vania-pooh** [comment]
@ruescar JFYI there will be tag 4.0.0 soon with full support for clipboard, waiting for window manager and devtools.

**Comment by ruescar** [comment]
Cool @vania-pooh. Looking forward to it! As the idea is to divert as minimum as possible from your master branch and potentially contributing.

**Comment by kolodiy** [comment]
Hi,
@vania-pooh are there any updates on this one? Are you going to officially support beta images any time soon?

**Comment by vania-pooh** [comment]
@kolodiy One of our next tasks is to create a CI server automatically building such images.

**Comment by vania-pooh** [comment]
This is now supported in build binary with `--channel` flag.

**Comment by bonigarcia** [comment]
@vania-pooh Great, thanks a lot. Do you plan to upload beta/dev images to Docker Hub?

**Comment by vania-pooh** [comment]
@bonigarcia uploading will be done when CI is ready.

**Comment by bonigarcia** [comment]
@vania-pooh Is there any update about the release of beta/dev images in Docker Hub? Thanks a lot for your work.

**Comment by vania-pooh** [comment]
@bonigarcia no resources for this task for the moment. Probably during next months.

**Comment by bonigarcia** [comment]
Great, thanks a lot again, @vania-pooh.

**Comment by ajsa-terko** [comment]
Hello, are there plans to support uploading beta/dev images to Docker Hub shortly? Thanks!
