### ISSUE TITLE
[Feature/Discussion] Add user-customizable layers

### ISSUE THREAD

**Issue by matthewdoerksen** [aerokube/images#288]
Our project has a number of layers that we add on to the base images (like certificates for Chrome/Firefox and test resources inside the containers for use by our selenium tests). It would be nice for us to be able to simply execute the build and have the project include our customizations.

What I want to start a conversation around is, would this project be open to me building the scaffolding to include user customizable layers (even though they wouldn't be used by the project directly) / would this be useful?

**Comment by vania-pooh** [comment]
@matthewdoerksen I don't get how to technically achieve this. Usually adding new layers is as simple as inheriting from existing Docker images and adding any desired stuff.
