### ISSUE TITLE
Supporting Safari

### ISSUE THREAD

**Issue by kaktaktoa** [aerokube/images#300]
Hi, everyone
The Selenium framework officially supports Safari 10 and newer. https://www.selenium.dev/documentation/en/getting_started_with_webdriver/browsers/

Can you support Safari?

**Comment by aandryashin** [comment]
Hello, Maks,

Selenoid can run safari on MacOS computers. Docker images are bases on
linux system, there is no safari distribution for linux.

вт, 13 окт. 2020 г., 11:36 Maks Kuznetsov <notifications@github.com>:

**Comment by vania-pooh** [comment]
@kaktaktoa related article: https://medium.com/@aandryashin/selenium-an-apple-story-ab0c0b68cd35

**Comment by kaktaktoa** [comment]
Ok, but what about Moon? Can i manage other browser at the same time? For example, crhome and safari.

**Comment by vania-pooh** [comment]
@kaktaktoa related stuff: https://aerokube.com/images/latest/#_safari
