### ISSUE TITLE
Add MicrosoftEdge image for Linux

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/images#302]
Driver: https://msedgedriver.azureedge.net/ for linux64.
Browser Deb repository: https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software#ubuntu

**Comment by mcahornsirup** [comment]
I could not find the image within dockerhub... are there any plans to make the prebuild image available?

**Comment by vania-pooh** [comment]
@mcahornsirup https://aerokube.com/images/latest/#_microsoft_edge
