### ISSUE TITLE
Video recording with sound

### ISSUE THREAD

**Issue by raduburla** [aerokube/images#321]
Hi,

First, thank you for this great piece of software, works out of the box like a charm.

I have a particular use case where a videoconference should be recorded and I need help figuring out if it's even posible to achieve.

As the title suggests, I need to record the selenoid browser session with sound.

Doing this on a server with no sound card might be tricky.

From my research the following steps should be taken:
1. enable on the host OS snd-dummy (https://superuser.com/questions/344760/how-to-create-a-dummy-sound-card-device-in-linux-server)
2. on the browser machine:
                        - install alsa-utils and define /etc/asound.conf
                        - install pulseaudio and add user running chrome to audio group (I don't know if this step is                       really required if my system does not have a sound card)

3. ffmpeg should be compiled with alsa support and should pick up the sound from the dummy sound card added

From all this I managed to do 1 by creating a custom docker image raduburla/chrome which works well, i think, chrome finds the sound devices and 2, the OS finds the virtual sound card.

With 3 I am unable to modify the image that records video, I might be missing some docker knowledge here.

The videos recorded by selenoid are still without sound.

I am missing something or what I am trying to achieve is not even possible?

Any help appreciated, thank you.

**Comment by GhaziTriki** [comment]
@aandryashin Thank you very much for the PR. It is pushing Selenoid into an upper level.

**Comment by wangjin** [comment]
Hi, I’m using Selenoid to record my tests screen which works pretty well. But the video recorded has no audio. I'm running Selenoid in Docker engine v20.10.11 on my mac(macOS 12.0.1) and all the settings are by default. So what else should I check? Any help appreciated, thank you.

**Comment by vania-pooh** [comment]
@wangjin it's currently broken. https://github.com/aerokube/images/issues/413

**Comment by wangjin** [comment]
@vania-pooh Thanks for the reply, I tried the old version of chrome image(88.0) and it works!
