### ISSUE TITLE
Question: how to import certificate in browser

### ISSUE THREAD

**Issue by mnjagadeesh** [aerokube/images#338]
hi,
Is there any way to import certificate in browser?

Thanks

**Comment by vania-pooh** [comment]
https://aerokube.com/images/latest/#_adding_custom_root_certification_authority

**Comment by mnjagadeesh** [comment]
Thanks for the link. Tried this method. Looks like I am missing something. Probably an example would extremely helpful.

**Comment by vania-pooh** [comment]
@mnjagadeesh need to set `env` capability with `ROOT_CA_xxxx` as key and base64-encoded CA certificate as value.

**Comment by mnjagadeesh** [comment]
> @mnjagadeesh need to set `env` capability with `ROOT_CA_xxxx` as key and base64-encoded root CA certificate as value.

In browsers.json. correct?

**Comment by nguyenanthony88** [comment]
@vania-pooh - I'm having the same problem. It's not clear which containers we are adding the variables: moon, moon-api, or selenoid-ui. Regardless, I've added to all of them including the browsers.json and haven't been able to get it to work. 

Are there any other tips or advice for troubleshooting? It would be great if the instructions had more details and examples.

**Comment by vania-pooh** [comment]
@mnjagadeesh in browsers.json or via capabilities.
@nguyenanthony88 will try to improve documentation about this feature.

**Comment by mnjagadeesh** [comment]
> @mnjagadeesh in browsers.json or via capabilities.
> @nguyenanthony88 will try to improve documentation about this feature.

Have tried both ways. No luck.


Thanks

**Comment by vania-pooh** [comment]
@mnjagadeesh you should import root certification authority certificate used to sign TLS certificates. Anything else will not work.

**Comment by mnjagadeesh** [comment]
"78.0": {
                "image": "selenoid/firefox:78.0",
                "volumes": [ "/home/njagadeesh/cert:/home/njagadeesh/cert:rw" ],
                "port": "4444",
                "env": ["CERT_CONTENTS=$(cat /home/njagadeesh/cert/cacert.der |  base64 -w0) ", 
 "ROOT_CA_JNM=$CERT_CONTENTS" ],
                "path": "/wd/hub"
            }
        }

========================================================================================

docker inspect:

       "StdinOnce": false,
            "Env": [
                "TZ=UTC",
                "SCREEN_RESOLUTION=1920x1080x24",
                "ENABLE_VNC=true",
                "ENABLE_VIDEO=false",
                "CERT_CONTENTS=$(cat /home/njagadeesh/cert/cacert.der |  base64 -w0) ",
                "ROOT_CA_JNM=$CERT_CONTENTS",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],

Is this correct or am I missing something?

Thanks

**Comment by vania-pooh** [comment]
@mnjagadeesh Docker will certainly not evaluate this expression `ROOT_CA_JNM=$CERT_CONTENTS` and `$CERT_CONTENTS` variable value will not be substituted. We never said that variable substitution works with Selenoid configuration files. It only works in command-line interpreter like Bash or Zsh.

**Comment by nguyenanthony88** [comment]
@mnjagadeesh if you have the base64 encoded cert contents, try doing this:
```
"ROOT_CA_JNM=LS0tL....==",
```
I'm curious if it will work for you because I have gotten nowhere

**Comment by mnjagadeesh** [comment]
I have tried 
$CERT_CONTENTS-$(cat /home/njagadeesh/cert/cacert.der |  base64 -w0)

Then copied  output of  `echo $CERT_CONTENTS` and pasted in place of XXXXX below

env: [ROOT_CA_JNM=XXXXX"]

But still no luck.

**Comment by mnjagadeesh** [comment]
> @mnjagadeesh if you have the base64 encoded cert contents, try doing this:
> 
> ```
> "ROOT_CA_JNM=LS0tL....==",
> ```
> 
> I'm curious if it will work for you because I have gotten nowhere

nope. not working for me.

**Comment by vania-pooh** [comment]
@mnjagadeesh should use plain test certificate file starting with `---BEGIN CERTIFICATE---`.

**Comment by VVakko** [comment]
@vania-pooh, please add an example of using the browsers.json file to the [documentation](https://aerokube.com/images/latest/#_adding_custom_root_certification_authority).
And if it is not difficult, write, starting with which versions of browsers this functionality works. I just spent a lot of time experimenting before I realized that this feature doesn't work in chrome:87, but it works in chrome:88. In firefox, it works in both: 84 and: 85.

**Comment by WendyZ123** [comment]
Hi all, 

I'm trying to import pfx certificate in browser (chrome) by referring to:
https://aerokube.com/images/latest/#_adding_custom_root_certification_authority
I placed cert config in browsers.json file:
"94.0": {
"image": "selenoid/vnc_chrome:94.0",
"volumes": [ "/home/user/cert:/home/user/cert:rw" ],
"port": "4444",
"env": ["CERT_CONTENTS=$(cat /home/user/cert/cacert.pem | base64 -w0) ",
"ROOT_CA_MY_CERT=---BEGIN CERTIFICATE---xxxx---END CERTIFICATE---.." ],
"path": "/"
}
}
But not working.
Please share an example about how to set it up. 
Thanks.

**Comment by vania-pooh** [comment]
@WendyZ123 should be base64-encoded.

**Comment by WendyZ123** [comment]
@vania-pooh I converted by following this: https://userapps.support.sap.com/sap/support/knowledge/en/2613693
But still no luck.
"94.0": {
"image": "selenoid/vnc_chrome:94.0",
"volumes": [ "/home/user/cert:/home/user/cert:rw" ],
"port": "4444",
"env": ["CERT_CONTENTS=$(cat /home/user/cert/cacert.cer | base64 -w0) ",
"ROOT_CA_MY_CERT=---BEGIN CERTIFICATE---xxxx---END CERTIFICATE---.." ],
"path": "/"
}
}
Is there anything else I'm missing?

**Comment by vania-pooh** [comment]
@WendyZ123 
```
$ echo '---BEGIN CERTIFICATE---' | base64
LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0K
```
So encoded value should certainly start with this string:

```
ROOT_CA_MY_CERT=LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0K....
```

**Comment by WendyZ123** [comment]
@vania-pooh 
I have updated config file as below:
"94.0": {
"image": "selenoid/vnc_chrome:94.0",
"volumes": [ "/home/user/cert:/home/user/cert:rw" ],
"port": "4444",
"env": ["CERT_CONTENTS=$(cat /home/user/cert/cacert.pem| base64 -w0) ",
"ROOT_CA_MY_CERT=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t..." ],
"path": "/"
}
}
But selenoid container still can NOT be started. 
Is there any where else I need to check?

**Comment by vania-pooh** [comment]
@WendyZ123 `CERT_CONTENTS` is not needed. Volumes is also not needed.

**Comment by VVakko** [comment]
> But selenoid container still can NOT be started.
> Is there any where else I need to check?

Here is my working version of the config:
```json
      "98.0": {
        "image": "selenoid/vnc_chrome:98.0",
        "port": "4444",
        "path": "/",
        "cpu": "2.0",
        "mem": "512m",
        "shmSize": 268435456,
        "tmpfs": {
          "/tmp": "size=256m"
        },
        "env": [
          "TZ=Europe/Moscow",
          "ROOT_CA_CORP_CA_Root01=LS0...==",
          "ROOT_CA_CORP_CA_Sub01=LS0...=="
        ]
      }
```
There are two certificates listed here: root and intermediate.

**Comment by vania-pooh** [comment]
@SublateSamuel this issue is about installing certification authority certificate which never contains a password. What you are probably talking about is a mutual TLS client certificate. We never said this is supported in our images.

**Comment by ViniciusEd** [comment]
hey guys,

I'm facing the same issue explained on this thread...

How can i import my SSL certificate to fix the messages "Your connection is not private", "This connection is untrusted", etc.

Below my browsers.json config:

{ "chrome":{ "default":"115.0", "versions":{ "115.0":{ "image":"selenoid/chrome:115.0", "port":"4444", "path":"/", "tmpfs":{ "/tmp":"size=128m" }, "env": [ "TZ=America/Sao_Paulo", "ROOT_CA_MY_CERT=LS0tLS1...=" ] }, "114.0":{ "image":"selenoid/chrome:114.0", "port":"4444", "path":"/", "tmpfs":{ "/tmp":"size=128m" } } } }, "firefox":{ "default":"115.0", "versions":{ "115.0":{ "image":"selenoid/firefox:115.0", "port":"4444", "path":"/wd/hub", "tmpfs":{ "/tmp":"size=128m" } }, "114.0":{ "image":"selenoid/firefox:114.0", "port":"4444", "path":"/wd/hub", "tmpfs":{ "/tmp":"size=128m" } } } } }

**Comment by vania-pooh** [comment]
@ViniciusEd you need to use certification authority certification, not ssl certificate itself in your config.

**Comment by ViniciusEd** [comment]
Yes @vania-pooh,

First of all, thanks for your time!

I've converted my certificate 'cert.pem' to base64 and pasted the result to "ROOT_CA_MY_CERT=LS0tLS1...=" on my browsers.json file, but i'm still facing the issue.

I followed the instructions of this link: https://aerokube.com/images/latest/#_adding_custom_root_certification_authority but i feel like there's something missing

**Comment by vania-pooh** [comment]
@ViniciusEd are you really really sure that you are using a CA certificate and NOT your domain name certificate? Both can have pem extension because both are PEM encoded.

**Comment by ViniciusEd** [comment]
Hey @vania-pooh,

I downloaded my 'cert.pem' from the browser itself.

I followed this step by step to obtain it: I clicked on the **padlock** in the upper left corner of the browser > and i clicked on '**The connection is secure**' > and i clicked on '**The certificate is valid**' > and i clicked on '**Details**' > and i selected the **first certificate from hierarchy** > and i clicked '**export**'.

Is this the certificate expected in the parameter 'ROOT_CA_MY_CERT'?

Another thing, is the configuration of my browsers.json file correct? Is it just this setting, or do I need to do something in the docker run command to?

_{ "chrome":{ "default":"115.0", "versions":{ "115.0":{ "image":"selenoid/chrome:115.0", "port":"4444", "path":"/", "tmpfs":{ "/tmp":"size=128m" }, "env": [ "TZ=America/Sao_Paulo", "ROOT_CA_MY_CERT=LS0tLS1...=" ] }, "114.0":{ "image":"selenoid/chrome:114.0", "port":"4444", "path":"/", "tmpfs":{ "/tmp":"size=128m" } } } }, "firefox":{ "default":"115.0", "versions":{ "115.0":{ "image":"selenoid/firefox:115.0", "port":"4444", "path":"/wd/hub", "tmpfs":{ "/tmp":"size=128m" } }, "114.0":{ "image":"selenoid/firefox:114.0", "port":"4444", "path":"/wd/hub", "tmpfs":{ "/tmp":"size=128m" } } } } }_

Thank you for your attention!

**Comment by vania-pooh** [comment]
@ViniciusEd you need to download root certification authority. Something like this: https://medium.com/@sanghviyash6/how-to-get-ca-certificate-of-any-server-using-google-chrome-e8db3e4d3fcf

**Comment by melquelima** [comment]
> TLS client certificate


This is a really good implementation if possible, there is no way to implement that?

**Comment by vania-pooh** [comment]
@melquelima we never tried.
