### ISSUE TITLE
firefox browser not honoring Port configuration

### ISSUE THREAD

**Issue by mnjagadeesh** [aerokube/images#339]
my capabilities configuration is 

capabilities: {
      browserName: 'firefox',
      version: "83",
      enableVNC: true,
        proxy: {
          proxyType: 'manual',
          'httpProxy': '192.168.0.9:9090',
         // 'httpProxy': '192.168.0.9:',
          httpPort: '9090',
      },
  }
};

but in log I see

PORT=5900
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
1612497216243   Marionette  INFO    Listening on port 41293
1612497216339   Marionette  INFO    Proxy settings initialised: {"proxyType":"manual","httpProxy":"192.168.0.9:80"}
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
I tried 
httpProxy: "192.168.0.9:9090" and
httpProxy: "192.168.0.9"
httpProxyPort: "9090"

proxy port is not set in browser.
Am I missing something?

**Comment by vania-pooh** [comment]
@mnjagadeesh there is no `httpPort` or `httpProxyPort` capability. Everything described in spec should work: https://www.w3.org/TR/webdriver/#proxy

**Comment by mnjagadeesh** [comment]
@vania-pooh tried httpProxyPort too. no luck. I tried with httpPort . I am using browser version 83.0. Will check with other lower version and let you know.

**Comment by mnjagadeesh** [comment]
looks like firefox:78.0  good one.
