### ISSUE TITLE
build and push "latest" image/tag for vnc images

### ISSUE THREAD

**Issue by vdelendik** [aerokube/images#364]
For now we have "latest" tag only for images without VNC support:
https://hub.docker.com/r/selenoid/firefox/tags?page=1&ordering=last_updated

Please, adjust you build process and produce and push into the hub docker "latest" image for vnc_chrome, vnc_firefox etc.

**Comment by vania-pooh** [comment]
@vdelendik we have plans to remove VNC images because now all images have VNC inside. Also we have plans moving everything under `browsers/*` namespace.

**Comment by vdelendik** [comment]
@vania-pooh, thanks for the explanation!
closing the ticket then
