### ISSUE TITLE
Question: How connect to Selenoid's Appium opencv4nodejs library (Visual regression Testing approach)

### ISSUE THREAD

**Issue by abayibrayev1** [aerokube/images#371]
I'm using Appium + opencv4nodejs locally (with android emulator and it works correctly, i'm able to check images similarity)

But i don't know how to connect external Appium libs to Selenoid impl. Do u have any docs about it? Or any ideas, how can I implement it? 
Thanks in advance!

**Comment by vania-pooh** [comment]
@abayibrayev1 this requires building Android images yourself. Just install this library to Android images. Source code can be found here: https://github.com/aerokube/images/tree/master/selenium/android
