### ISSUE TITLE
unable to pull selenoid/edge:89.0

### ISSUE THREAD

**Issue by mnjagadeesh** [aerokube/images#372]
$ docker pull selenoid/edge:89.0
Error response from daemon: pull access denied for selenoid/edge, repository does not exist or may require 'docker lo
gin': denied: requested access to the resource is denied

**Comment by vania-pooh** [comment]
@mnjagadeesh correct image ref is `browsers/edge:89.0`. https://aerokube.com/images/latest/#_microsoft_edge

**Comment by mnjagadeesh** [comment]
Thanks. It is working now.
