### ISSUE TITLE
Auto-Update for Edge pulls a lot of data

### ISSUE THREAD

**Issue by benzman81** [aerokube/images#373]
Our IT department noticed, that there is a lot of data pulled from servers like assets.msn.com, edge.microsoft.com, img-s-msn-com.akamaized.... and others. This seems to be the update mechanism of Edge. More than 200GB of data was fetched from these servers just for a single day of tests (about 3-4 test runs with each about 4.500 Tests). I can reproduce this by watching the traffic and manually starting an instance of Edge using seleniod by creating the session manually.
Currently we use version 89.0 and we know that there are updates available. But we want to stay on a defined version for now.
Is there a possibility to turn that update mechanism off?

**Comment by vania-pooh** [comment]
@benzman81 we'll try to investigate. What we install is official Debian distribution of Microsoft Edge.

**Comment by benzman81** [comment]
Some more info, if needed, this is the result for two edge instances manually created.

![ntopng](https://user-images.githubusercontent.com/14224592/113733327-a50cc500-96fa-11eb-9efe-09801fb401d3.png)

**Comment by benzman81** [comment]
@vania-pooh for now, we solved it by putting the following into
