### ISSUE TITLE
How do I pass ROOT_CA_MY_CERT to the browser image

### ISSUE THREAD

**Issue by JoyceBabu** [aerokube/images#375]
How do I pass `ROOT_CA_MY_CERT` to the browser image? Do I have to create a custom image for all browsers?

Is it possible to load this data from `.env` file?

**Comment by aandryashin** [comment]
It is described here:

https://aerokube.com/images/latest/#_adding_custom_root_certification_authority

чт, 15 апр. 2021 г., 11:55 Joyce Babu ***@***.***>:

**Comment by JoyceBabu** [comment]
@aandryashin Thank you for the response. I did see that, and hence my question.

After doing some research, I found two ways to pass the environment variable.

- Add the encoded certificate directly under the `env` key of `browsers.json`.
   ```
   "env": ["ROOT_CA_MY_CERT=LS0tL....=="]
   ```
- Add the environment variable directly to the browser image, by extending the base browser image.
  ```
  FROM selenoid/vnc:chrome_89.0
  ENV ROOT_CA_MY_CERT="LS0tL....=="
  ```

But I would like to keep the encoded certificate, which in my case is environment specific, outside version control within an environment file.

Docker supports passing the environment variable from the host directly to the container by specifying just the variable name.  I tried adding the environment variable to the `selenoid` container through `docker-compose.yml` (which supports loading environment variables from `.env` file), and setting just the variable name in `browsers.json` as below

```
"env": ["ROOT_CA_MY_CERT"]
```

But it did not work.

**Comment by vania-pooh** [comment]
@JoyceBabu an expected way is adding to `env` in `browsers.json`:
```
"env": ["ROOT_CA_MY_CERT=LS0tL....=="]
```

**Comment by JoyceBabu** [comment]
@vania-pooh Thank you. That is how I am currently doing it.

It is possible to add support for passing the environment variables directly from the selenoid container, similar to how docker handles environment variables without value?

```
export FOO=bar
docker run -ti -e FOO  bash echo $FOO
```

https://docs.docker.com/compose/environment-variables/#pass-environment-variables-to-containers

**Comment by vania-pooh** [comment]
@JoyceBabu you can pass `env` from capabilities too.  https://aerokube.com/selenoid/latest/#_per_session_environment_variables_env

**Comment by JoyceBabu** [comment]
@vania-pooh I tried adding 

```
selenoidOptions: {
    env: [
        `ROOT_CA_MY_CERT=${process.env.ROOT_CA_MY_CERT}`
    ],
},
```

to `desiredCapabilities` and it worked perfectly. Thank you.
