### ISSUE TITLE
Connect to browser container with a VNC client

### ISSUE THREAD

**Issue by bonigarcia** [aerokube/images#381]
Hello,

I am using Chrome in Docker (without Selenoid) as follows:

```
docker run --rm --cap-add=SYS_ADMIN -p 4444:4444 -p 5900:5900 selenoid/vnc:chrome_90.0
```

Now I want to connect to the container using a VNC client using the following setup:

* URL: vnc://localhost:5900
* Password: selenoid

I think I was able to this in the past, but now, the connection cannot be established for some reason.

Am I doing something wrong?

Thanks a lot in advance.

**Comment by vania-pooh** [comment]
@bonigarcia should add `-e ENABLE_VNC=true` to actually start VNC server.

**Comment by bonigarcia** [comment]
Indeed, I forget that one. Thanks a lot @vania-pooh!

**Comment by bonigarcia** [comment]
Sorry to disturb again. I have just faced a different problem related to this.

After starting the browser as follows:

```
docker run --rm --cap-add=SYS_ADMIN -p 4444:4444 -p 5900:5900 -e ENABLE_VNC=true -e ENABLE_WINDOW_MANAGER=true selenoid/vnc:chrome_90.0
```

... now I want to connect to the container using noVNC. For that, I start the following container:

```
docker run --rm -p 8080:8080 psharkey/novnc:3.3-t6
```

... and then I connect to:

http://172.17.0.1:8080/vnc.html?host=172.17.0.1&port=5900&resize=scale&autoconnect=true&password=selenoid

Everything seems to work nicely, since I can see the container desktop (without browser, so far):

![Screenshot from 2021-05-12 15-30-10](https://user-images.githubusercontent.com/5413013/117983368-2cbba400-b337-11eb-8a34-960099df49f3.png)

But when I try to interact with noVNC, the connection is disconnected automatically:

![Screenshot from 2021-05-12 15-34-52](https://user-images.githubusercontent.com/5413013/117983897-a784bf00-b337-11eb-9e08-39a104692695.png)

Do you know why is the session disconnected?

Maybe this is a issue of noNVC, I'm not sure. Thanks a lot for your time, @vania-pooh.

**Comment by vania-pooh** [comment]
@bonigarcia no, not sure about the reason. Selenoid UI is also based on noVNC, so should work.

**Comment by bonigarcia** [comment]
I continue struggling with this. I think I found the reason, but I am not sure how to solve it.

The noVNC container is working properly. I checked by connecting the same noVNC container to selenoid (with a running browser session). The difference with my previous approach is now, the **path** is available in the noVNC URL (composed by `vnc/` plus the session id):

http://172.17.0.1:8080/vnc.html?host=172.17.0.1&port=4444&path=vnc/b2a71261b248a87f736a99b8aaa9e94e&autoconnect=true&password=selenoid

That path is missing in the URL I am using to connect directly to the Docker container (i.e., without Selenoid):

http://172.17.0.1:8080/vnc.html?host=172.17.0.1&port=5900&autoconnect=true&password=selenoid

In the second case (using directly Chrome in Docker without Selenoid), when I interact with the browser through noVNC (e.g., moving the mouse on the screen), the **websocket** is closed (I checked this in the browser console), and as a result, the session is disconnected. It seems that selenoid acts as websocket server, and that is something missing in the approach I am trying in implement (i.e., connect noVNC to a standalone Chrome in Docker).

**Comment by bonigarcia** [comment]
I found the solution. It was not the path, as I suspected before. It seems it is related in how the noVNC is configured and executed. I have changed to this image and everything works as expected:

```
docker run --rm -p 8080:6080 gotget/novnc --vnc 172.17.0.1:5900
```
