### ISSUE TITLE
Update  tags to the chrome images

### ISSUE THREAD

**Issue by Westmar** [aerokube/images#399]
Hi, is it possible to update Chrome tags from https://hub.docker.com/r/selenoid/chrome/tags ?
The latest version is now 88. Although the latest version should update the browser version every time(ex: selenoid/chrome:latest = 91). And it hasn't changed for more than 5 months.

**Comment by vania-pooh** [comment]
<img width="1271" alt="Screen Shot 2021-06-23 at 11 00 58" src="https://user-images.githubusercontent.com/829320/123059339-58d84380-d412-11eb-9bf3-af146c591bf4.png">

Are you sure?

**Comment by Westmar** [comment]
@vania-pooh 
Apparently, I described it incorrectly :(
I am using the command: docker pull selenoid/chrome:latest
And this image is equal to chrome 88.
Is it possible to update versioning?
The latest release version of chrome is equal to the 'latest' tag.
Example: selenoid/chrome:latest => selenoid/chrome:91.0

**Comment by vania-pooh** [comment]
@Westmar done, but we consider this a bad practice.
