### ISSUE TITLE
New Image for FF 90

### ISSUE THREAD

**Issue by theproshin** [aerokube/images#407]
Create please image for FF 90
https://www.mozilla.org/en-US/firefox/90.0/releasenotes/

**Comment by vania-pooh** [comment]
Waiting for respective package to appear in repository.

**Comment by theproshin** [comment]
Can I create image to your instaruction http://aerokube.com/images/latest/#_building_images on OS Windows or only build on Ubuntu?

**Comment by vania-pooh** [comment]
@theproshin you can using this one: https://github.com/aerokube/windows-images
