### ISSUE TITLE
Add chrome 93

### ISSUE THREAD

**Issue by PetrSukhov2015** [aerokube/images#437]
Add chrome 93

**Comment by theproshin** [comment]
You can use images from https://hub.docker.com/r/theproshin/chrome/
it was built to the selenoid doc http://aerokube.com/images/latest/#_building_images

**Comment by emwil** [comment]
Is it possible to add an image selenoid/vnc_chrome:93.0 with ChromeDriver 95.0.4638.10? This version fixes the problem: Resolved issue 3857: Host header or origin header is specified and is not whitelisted or localhost [Pri-1]

**Comment by vania-pooh** [comment]
Fixed.
@emwil desired driver version will only work with Chrome 95.x
