### ISSUE TITLE
how to build a arm64 chrome image?

### ISSUE THREAD

**Issue by rubyangxg** [aerokube/images#449]
how to build a arm64 chrome image?

**Comment by vania-pooh** [comment]
@rubyangxg this requires investigation. We at least need to switch to arm64 Debian repository and arm64 base Ubuntu image.`

**Comment by Juice10** [comment]
@vania-pooh would this make it easier to run on arm64 for puppeteer? https://github.com/microsoft/playwright/issues/7723#issuecomment-964702224

**Comment by vania-pooh** [comment]
@Juice10 Playwright guys are preparing their patched versions of Chrome browser. We are currently waiting for the Mac machine with M1 CPU in order to go forward with everything related to arm64.

**Comment by Juice10** [comment]
@vania-pooh if you have a raspberry pi lying around they are also arm64

**Comment by vania-pooh** [comment]
@Juice10 we don't have it.

**Comment by sskorol** [comment]
@rubyangxg @Juice10 I've just created a draft PR with a build script for arm64 Chromium. Feel free to check it out for testing. Note that I tested only a limited set of features on M1 MacBook: basically the fact that it just works with VNC and video recording.
