### ISSUE TITLE
Rejecting request with host: XX.XX.XXX.XXX:4444 address: XX.XX.XXX.XXX

### ISSUE THREAD

**Issue by emwil** [aerokube/images#474]
I have this error when running tests on the chrome browser from version 92 to 95. I used the CLI flag: --allowed-origin="*". But it didn't help.

Starting ChromeDriver 95.0.4638.17 (a9d0719444d4b035e284ed1fce73bf6ccd789df2-refs/branch-heads/4638@{#178}) on port 4444
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
 --- x11vnc loop: waiting for: 196

[1635953512.290][SEVERE]: Rejecting request with host: XX.XX.XXX.XXX:4444 address: XX.XX.XXX.XXX
PORT=5900

Does anyone have any solution?

**Comment by vania-pooh** [comment]
@emwil ok, added new `browsers/chrome:96.0` (or `selenoid/chrome:96.0`) image where `--allowed-origins` flag is added. Could you try with it?

**Comment by emwil** [comment]
@vania-pooh I try this image. It's work. Can you add this flag to future images? Is there a chance that you would also add this flag by default to images with chroma 93, 94, 95?

**Comment by vania-pooh** [comment]
@emwil all future images will contain this flag. However I don't think will rebuild previous ones right now.

**Comment by emwil** [comment]
@vania-pooh Ok, thanks.

**Comment by vania-pooh** [comment]
Closing this then.
