### ISSUE TITLE
firefox vesrion 95 with vnc failing  with options added to FirefoxOptions

### ISSUE THREAD

**Issue by udifaintuch** [aerokube/images#486]
when I run the automation test without the options added , it able to open but when I add the options it failed to open ( meaning open the container but failing in creating the firefox )
the same code work fine for firefox vnc version 94 ( with or without the options )

the firefox options  object looks like that:
{{
  "browserName": "firefox",
  "acceptInsecureCerts": true,
  "moz:firefoxOptions": {
    "args": [
      "Incognito",
      "start-maximized"
    ]
  },
  "name": "TEST_56",
  "enableVNC": true
}}rowserName": "firefox",
  "acceptInsecureCerts": true,
  "moz:firefoxOptions": {
    "args": [
      "Incognito",
      "start-maximized"
    ]
  },
  "name": "TEST_56",
  "enableVNC": true
}}

and it works with vesrion 94 and do not work in vesrion 95 of firefox
reproduce in selenium webdriver 4.1.0 and 3.141.0.
Also I am using the newest aerokube/selenoid image

Thanks and Best Regards

**Comment by vania-pooh** [comment]
@udifaintuch need exact error message you are getting.

**Comment by udifaintuch** [comment]
Thank you on your quick response !
the error that I get from the test is : OpenQA.Selenium.WebDriverException: 'New session attempts retry count exceeded'
I also extracted the docker logs for vesrion 94 ( which is working ) and vesrion 95 ( which is failing ):
**it is seems similar but we have some differences like this two lines below which is in the 'x11vnc loop: 1' for version 95 while on vesrion 94 it's outside of the loop
[INIT] [Loading configuration files...]
[INIT] [Loaded configuration from /tmp/browsers.json]**

I will also atach the docker logs:
----------------------------------------------------------------------------------------
**version 95:**
20
Waiting X server...
Logging to: /dev/null
Waiting X server...

 --- x11vnc loop: 1 ---

2021/12/22 22:00:16 [-] [INIT] [Loading configuration files...]
2021/12/22 22:00:16 [-] [INIT] [Loaded configuration from /tmp/browsers.json]
2021/12/22 22:00:16 [-] [INIT] [Timezone: UTC]
2021/12/22 22:00:16 [-] [INIT] [Listening on :4444]
2021/12/22 22:00:16 [-] [NEW_REQUEST] [unknown] [172.17.0.2]
2021/12/22 22:00:16 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.2]
2021/12/22 22:00:16 [0] [LOCATING_SERVICE] [firefox] []
2021/12/22 22:00:16 [-] [DEFAULT_VERSION] [Using default version: 95.0]
2021/12/22 22:00:16 [0] [USING_DRIVER] [firefox] [95.0]
2021/12/22 22:00:16 [0] [ALLOCATING_PORT]
2021/12/22 22:00:16 [0] [ALLOCATED_PORT] [42597]
2021/12/22 22:00:16 [0] [STARTING_PROCESS] [[/usr/bin/geckodriver --port=42597]]
1640210416495   geckodriver     INFO    Listening on 127.0.0.1:42597
2021/12/22 22:00:16 [0] [PROCESS_STARTED] [109] [0.05s]
2021/12/22 22:00:16 [0] [PROXY_TO] [http://127.0.0.1:42597]
2021/12/22 22:00:16 [0] [SESSION_ATTEMPTED] [http://127.0.0.1:42597] [1]
1640210416547   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "--marionette" "Incognito" "start-maximized" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilerq6cRU"
[GFX1-]: glxtest: libpci missing
[GFX1-]: glxtest: libEGL missing
1640210416898   Marionette      INFO    Marionette enabled
 --- x11vnc loop: waiting for: 240

PORT=5900
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /tmp/rust_mozprofilerq6cRU/search.json.mozlz4", (void 0)))
1640210417884   Marionette      INFO    Listening on port 35311
1640210417959   RemoteAgent     WARN    TLS certificate errors will be ignored for this session
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.

-------------------------------------------------------------

**version:94**
20
Waiting X server...
Logging to: /dev/null
Waiting X server...
2021/12/22 22:07:31 [-] [INIT] [Loading configuration files...]
2021/12/22 22:07:31 [-] [INIT] [Loaded configuration from /tmp/browsers.json]

 --- x11vnc loop: 1 ---

2021/12/22 22:07:31 [-] [INIT] [Timezone: UTC]
2021/12/22 22:07:31 [-] [INIT] [Listening on :4444]
2021/12/22 22:07:31 [-] [NEW_REQUEST] [unknown] [172.17.0.2]
2021/12/22 22:07:31 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.2]
2021/12/22 22:07:31 [0] [LOCATING_SERVICE] [firefox] []
2021/12/22 22:07:31 [-] [DEFAULT_VERSION] [Using default version: 94.0]
2021/12/22 22:07:31 [0] [USING_DRIVER] [firefox] [94.0]
2021/12/22 22:07:31 [0] [ALLOCATING_PORT]
2021/12/22 22:07:31 [0] [ALLOCATED_PORT] [38451]
2021/12/22 22:07:31 [0] [STARTING_PROCESS] [[/usr/bin/geckodriver --port=38451]]
1640210851558   geckodriver     INFO    Listening on 127.0.0.1:38451
2021/12/22 22:07:31 [0] [PROCESS_STARTED] [109] [0.05s]
2021/12/22 22:07:31 [0] [PROXY_TO] [http://127.0.0.1:38451]
2021/12/22 22:07:31 [0] [SESSION_ATTEMPTED] [http://127.0.0.1:38451] [1]
1640210851610   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "--marionette" "Incognito" "start-maximized" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile4kKlE3"
[GFX1-]: glxtest: libpci missing
[GFX1-]: glxtest: libEGL missing
1640210851958   Marionette      INFO    Marionette enabled
 --- x11vnc loop: waiting for: 243

PORT=5900
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /tmp/rust_mozprofile4kKlE3/search.json.mozlz4", (void 0)))
1640210852899   Marionette      INFO    Listening on port 44813
1640210852930   RemoteAgent     WARN    TLS certificate errors will be ignored for this session
2021/12/22 22:07:32 [0] [SESSION_CREATED] [faf8e716-ef06-4695-829f-2b0de988440c] [1] [1.38s]
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.

**Comment by vania-pooh** [comment]
@udifaintuch `enableVNC` should live under `selenoid:options` capability. https://aerokube.com/selenoid/latest/#_specifying_capabilities_via_protocol_extensions Probably in version 95.0 they made this check strict.

**Comment by udifaintuch** [comment]
@vania-pooh  still not working...
now I don't get any error from the code but the firefox are not created.

the firefox options object looks like that now :
{{
  "browserName": "firefox",
  "acceptInsecureCerts": true,
  "selenoid:options": {
    "name": "TEST_56
    "enableLog": false,
    "logName": "TEST_56.log",
    "enableVNC": true
  },
  "moz:firefoxOptions": {
    "args": [
      "Incognito",
      "start-maximized"
    ]
  }
}}

**and the docker logs like that:**
20
Waiting X server...
Logging to: /dev/null
Waiting X server...
2021/12/23 14:11:42 [-] [INIT] [Loading configuration files...]

 --- x11vnc loop: 1 ---

2021/12/23 14:11:42 [-] [INIT] [Loaded configuration from /tmp/browsers.json]
2021/12/23 14:11:42 [-] [INIT] [Timezone: UTC]
2021/12/23 14:11:42 [-] [INIT] [Listening on :4444]
2021/12/23 14:11:42 [-] [NEW_REQUEST] [unknown] [172.17.0.2]
2021/12/23 14:11:42 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.2]
2021/12/23 14:11:42 [0] [LOCATING_SERVICE] [firefox] []
2021/12/23 14:11:42 [-] [DEFAULT_VERSION] [Using default version: 95.0]
2021/12/23 14:11:42 [0] [USING_DRIVER] [firefox] [95.0]
2021/12/23 14:11:42 [0] [ALLOCATING_PORT]
2021/12/23 14:11:42 [0] [ALLOCATED_PORT] [37147]
2021/12/23 14:11:42 [0] [STARTING_PROCESS] [[/usr/bin/geckodriver --port=37147]]
1640268702934   geckodriver     INFO    Listening on 127.0.0.1:37147
2021/12/23 14:11:42 [0] [PROCESS_STARTED] [109] [0.05s]
2021/12/23 14:11:42 [0] [PROXY_TO] [http://127.0.0.1:37147]
2021/12/23 14:11:42 [0] [SESSION_ATTEMPTED] [http://127.0.0.1:37147] [1]
1640268702987   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "--marionette" "Incognito" "start-maximized" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilelNsjkZ"
[GFX1-]: glxtest: libpci missing
[GFX1-]: glxtest: libEGL missing
1640268703328   Marionette      INFO    Marionette enabled
 --- x11vnc loop: waiting for: 241

PORT=5900
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /tmp/rust_mozprofilelNsjkZ/search.json.mozlz4", (void 0)))
1640268704337   Marionette      INFO    Listening on port 39291
1640268704402   RemoteAgent     WARN    TLS certificate errors will be ignored for this session
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.

**Comment by vania-pooh** [comment]
@udifaintuch try to add `VERBOSE=true` environment variable via `env` capability and take a look at browser container logs one more time.

**Comment by udifaintuch** [comment]
@vania-pooh 
just to make sure I understand you correctly.
I have added this line to browsers.json under vesrion FF 95:
"env": ["VERBOSE=true"].
still failing.
firefox options object remain the same.
Docker logs:
20
Waiting X server...
Logging to: /dev/null
Waiting X server...
2021/12/23 15:13:10 [-] [INIT] [Loading configuration files...]

 --- x11vnc loop: 1 ---

2021/12/23 15:13:10 [-] [INIT] [Loaded configuration from /tmp/browsers.json]
2021/12/23 15:13:10 [-] [INIT] [Timezone: UTC]
2021/12/23 15:13:10 [-] [INIT] [Listening on :4444]
2021/12/23 15:13:10 [-] [NEW_REQUEST] [unknown] [172.17.0.2]
2021/12/23 15:13:10 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.2]
2021/12/23 15:13:10 [0] [LOCATING_SERVICE] [firefox] []
2021/12/23 15:13:10 [-] [DEFAULT_VERSION] [Using default version: 95.0]
2021/12/23 15:13:10 [0] [USING_DRIVER] [firefox] [95.0]
2021/12/23 15:13:10 [0] [ALLOCATING_PORT]
2021/12/23 15:13:10 [0] [ALLOCATED_PORT] [41621]
2021/12/23 15:13:10 [0] [STARTING_PROCESS] [[/usr/bin/geckodriver --log debug --port=41621]]
1640272390135   geckodriver     INFO    Listening on 127.0.0.1:41621
2021/12/23 15:13:10 [0] [PROCESS_STARTED] [110] [0.05s]
2021/12/23 15:13:10 [0] [PROXY_TO] [http://127.0.0.1:41621]
2021/12/23 15:13:10 [0] [SESSION_ATTEMPTED] [http://127.0.0.1:41621] [1]
1640272390185   webdriver::server       DEBUG   -> POST /session {"capabilities":{"firstMatch":[{"acceptInsecureCerts":true,"browserName":"firefox","moz:firefoxOptions":{"args":["Incognito","start-maximized"]}}]}}
1640272390186   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "--marionette" "Incognito" "start-maximized" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilecqrENS"
1640272390187   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1:39735
[GFX1-]: glxtest: libpci missing
[GFX1-]: glxtest: libEGL missing
1640272390536   Marionette      INFO    Marionette enabled
 --- x11vnc loop: waiting for: 243

PORT=5900
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /tmp/rust_mozprofilecqrENS/search.json.mozlz4", (void 0)))
1640272391556   RemoteAgent     DEBUG   Setting recommended pref apz.content_response_timeout to 60000
1640272391556   RemoteAgent     DEBUG   Setting recommended pref browser.contentblocking.introCount to 99
1640272391557   RemoteAgent     DEBUG   Setting recommended pref browser.download.panel.shown to true
1640272391557   RemoteAgent     DEBUG   Setting recommended pref browser.newtabpage.enabled to false
1640272391558   RemoteAgent     DEBUG   Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1640272391558   RemoteAgent     DEBUG   Setting recommended pref browser.search.update to false
1640272391558   RemoteAgent     DEBUG   Setting recommended pref browser.tabs.disableBackgroundZombification to false
1640272391558   RemoteAgent     DEBUG   Setting recommended pref browser.tabs.unloadOnLowMemory to false
1640272391558   RemoteAgent     DEBUG   Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1640272391558   RemoteAgent     DEBUG   Setting recommended pref browser.tabs.warnOnOpen to false
1640272391559   RemoteAgent     DEBUG   Setting recommended pref browser.toolbars.bookmarks.visibility to never
1640272391559   RemoteAgent     DEBUG   Setting recommended pref browser.usedOnWindows10.introURL to
1640272391559   RemoteAgent     DEBUG   Setting recommended pref browser.urlbar.suggest.searches to false
1640272391559   RemoteAgent     DEBUG   Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1640272391560   RemoteAgent     DEBUG   Setting recommended pref dom.disable_open_during_load to false
1640272391560   RemoteAgent     DEBUG   Setting recommended pref dom.file.createInChild to true
1640272391560   RemoteAgent     DEBUG   Setting recommended pref dom.max_chrome_script_run_time to 0
1640272391560   RemoteAgent     DEBUG   Setting recommended pref dom.max_script_run_time to 0
1640272391560   RemoteAgent     DEBUG   Setting recommended pref dom.push.connection.enabled to false
1640272391560   RemoteAgent     DEBUG   Setting recommended pref dom.successive_dialog_time_limit to 0
1640272391561   RemoteAgent     DEBUG   Setting recommended pref extensions.getAddons.cache.enabled to false
1640272391561   RemoteAgent     DEBUG   Setting recommended pref extensions.getAddons.discovery.api_url to data:,
1640272391561   RemoteAgent     DEBUG   Setting recommended pref network.http.prompt-temp-redirect to false
1640272391561   RemoteAgent     DEBUG   Setting recommended pref privacy.trackingprotection.enabled to false
1640272391561   RemoteAgent     DEBUG   Setting recommended pref security.fileuri.strict_origin_policy to false
1640272391561   RemoteAgent     DEBUG   Setting recommended pref security.notification_enable_delay to 0
1640272391561   RemoteAgent     DEBUG   Setting recommended pref signon.autofillForms to false
1640272391562   RemoteAgent     DEBUG   Setting recommended pref signon.rememberSignons to false
1640272391562   RemoteAgent     DEBUG   Setting recommended pref browser.topsites.contile.enabled to false
1640272391563   RemoteAgent     DEBUG   Setting recommended pref dom.disable_beforeunload to true
1640272391563   Marionette      INFO    Listening on port 39735
1640272391564   Marionette      DEBUG   Marionette is listening
1640272391594   Marionette      DEBUG   Accepted connection 0 from 127.0.0.1:40190
1640272391595   geckodriver::marionette DEBUG   Connection to Marionette established on 127.0.0.1:39735.
1640272391598   Marionette      DEBUG   0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox"}]
1640272391599   RemoteAgent     WARN    TLS certificate errors will be ignored for this session
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.

**Comment by udifaintuch** [comment]
@vania-pooh 
I manage to fix the problem.
the code was using AddArguments and I changed it to use AddAdditionalOption and now it works.
it seems that it's not working if the object contain the 'moz:firefoxOptions' for some reason in vesrion 95
The firefox options object look like that:
{{
  "browserName": "firefox",
  "acceptInsecureCerts": true,
  "Incognito": true,
  "start-maximized": true,
  "selenoid:options": {
    "name": "TEST_56 -[WEB] Autologin Flow-Make a login with Keep me Logged-In option",
    "enableLog": false,
    "logName": "TEST_56 -[WEB] Autologin Flow-Make a login with Keep me Logged-In option.log",
    "enableVNC": true
  },
  "moz:firefoxOptions": {}
}}

**Comment by vania-pooh** [comment]
@udifaintuch closing then/

**Comment by udifaintuch** [comment]
Hi @vania-pooh 
sorry on the late response.
Yes , can  be closed.
Thanks.
