### ISSUE TITLE
adb devices unauthorized after a few days

### ISSUE THREAD

**Issue by suresach** [aerokube/images#508]
I'm running android emulator x86_64 android 11  on docker, for a few days things are good but without any error log `adb devices` returns unauthorized and a connection with appium can't be setup, I have tried restarting the container, emulator but nothing works. The only solution is to create a new container. Any idea what could be the issue or how to check logs if any?

**Comment by suresach** [comment]
have tried restarting adb, grating permission from emulator ui for usb debugging with no luck, @vania-pooh please help

**Comment by vania-pooh** [comment]
@suresach we never recommended running our browser images for days. You should use them for 1 sessions and then stop. This is what Selenoid \ Moon are actually doing.

**Comment by suresach** [comment]
alright thanks, any other images would you recommend which can be used for multiple days?

**Comment by vania-pooh** [comment]
@suresach not sure about it.
