### ISSUE TITLE
google-chrome-stable was not found for everythng but 99.0.4844.84-1

### ISSUE THREAD

**Issue by NathanFRuiz** [aerokube/images#512]
I'm trying to build custom images adding some steps to the source code, however anything other than -b 99.0.4844.84-1 will fail with error:

E: Version 'xx.x.xxx.xx-x' for 'google-chrome-stable' was not found

Example:

./images chrome -b 98.0.4758.80-1 -d 98.0.4758.80 -t selenoid-chrome:98.0

fails with:

E: Version '98.0.4758.80-1' for 'google-chrome-stable' was not found

Is that a expected behavior? if so is there anyway to build images with older chromedriver versions?

**Comment by vania-pooh** [comment]
@NathanFRuiz yes this is expected because Google Chrome team removes packages for old releases. You need to take packages from third-party resources. Chromedriver binaries for all versions are available for download [here](https://chromedriver.storage.googleapis.com/index.html).

**Comment by NathanFRuiz** [comment]
@vania-pooh  thanks for the quick answer. Just in case anyone gets to the same issue, since I was already making adjustments to the image, I chose to install chrome in another way so it can accept older versions of google-chrome-stable. I don't know if there will be any negative impacts though.

in chrome/apt/Dockerfile
```
RUN \
#        curl -s https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
#        echo 'deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google.list && \
#        apt-get -y --no-install-recommends install iproute2 $PACKAGE=$VERSION && \
        apt-get update && \
        apt-get -y --no-install-recommends install iproute2 && \
        curl -o /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/${PACKAGE}_${VERSION}_amd64.deb && \
        apt install -y /tmp/chrome.deb && \
        rm /tmp/chrome.deb && \
        sed -i -e 's@exec -a "$0" "$HERE/chrome"@& --no-sandbox --disable-gpu@' /opt/google/$INSTALL_DIR/google-chrome && \
        chown root:root /opt/google/$INSTALL_DIR/chrome-sandbox && \
        chmod 4755 /opt/google/$INSTALL_DIR/chrome-sandbox && \
        google-chrome --version && \
        rm -Rf /tmp/* && rm -Rf /var/lib/apt/lists/*
```
