### ISSUE TITLE
Unable to upload file with selenide

### ISSUE THREAD

**Issue by sytnykma-ss** [aerokube/images#529]
Since selenium 4.0 released and newest versions I started getting this error when trying to upload file:
UnsupportedCommandException: unknown command: unknown command: session/f6ad259d39d4b1f9be1e1861fa831db6/se/file
Screenshot: file:/home/circleci/unified-messaging-service-tests/build/reports/tests/1652857847769.34.png
Timeout: 7 s.
Caused by: UnsupportedCommandException: unknown command: unknown command: session/f6ad259d39d4b1f9be1e1861fa831db6/se/file

Using always - image: selenoid/chrome:latest 
Investigated a little and found out that 3+ versions of selenium worked without /se/file, so it was only /file as selenoid, for now I think selenoid still waits for /file and can't work with /se/file

**Comment by vania-pooh** [comment]
@sytnykma-ss yes, this change was done on Selenium side. Currently this was fixed in Moon only.

**Comment by sytnykma-ss** [comment]
> @sytnykma-ss yes, this change was done on Selenium side. Currently this was fixed in Moon only.

Ok but when it will be fixed on the selenoid/chrome?

**Comment by aandryashin** [comment]
Please update selenoid:

https://github.com/aerokube/selenoid/blob/master/selenoid.go#L525

ср, 18 мая 2022 г., 16:05 Maksym Sytnykov ***@***.***>:

**Comment by sytnykma-ss** [comment]
@aandryashin as I mentioned, I use image: selenoid/chrome:latest and it's not work there

**Comment by aandryashin** [comment]
Please make sure that you are using exactly that image:

https://hub.docker.com/layers/selenoid/aerokube/selenoid/1.10.7/images/sha256-2e3b71da1f5f5302f239f806cbe9cd6010f9cd8d496d25ade74e89fde8eed1c5?context=explore

ср, 18 мая 2022 г., 16:05 Maksym Sytnykov ***@***.***>:

**Comment by aandryashin** [comment]
selenoid/chrome is browser image, and what you are trying to use on circle
ci is aerokube/selenoid, they are completely different, btw you cannot run
selenoid on circle ci because it denies privileged mode, try to setup
standalone chrome image...

ср, 18 мая 2022 г., 22:34 Maksym Sytnykov ***@***.***>:

**Comment by vania-pooh** [comment]
@sytnykma-ss we will not fix this in `selenoid/chrome` because Chromedriver is a binary developer and maintained by Google. In this binary file upload API is still at `/file`.

**Comment by sytnykma-ss** [comment]
@vania-pooh @aandryashin Thank you guys for your answers! For those who met this problem - just use - image: selenium/standalone-chrome:latest instead
