### ISSUE TITLE
Running chrome-mobile container from the command line

### ISSUE THREAD

**Issue by bonigarcia** [aerokube/images#549]
Hi,

I used to run `chrome-mobile` from the command line as follows:

```
docker run --rm --cap-add=SYS_ADMIN -p 4444:4444 -p 5900:5900 -e ENABLE_VNC=true -e QTWEBENGINE_DISABLE_SANDBOX=1 --privileged selenoid/chrome-mobile:86.0
```

Nevertheless, the Android device in Docker does not start properly now. I see the following logs in the container (the line `adb: device offline` repeats forever):

```
Waiting X server...
Logging to: /tmp/fluxbox.log
Waiting X server...
* daemon not running; starting now at tcp:5037

 --- x11vnc loop: 1 ---

* daemon started successfully
adb: no devices/emulators found
 --- x11vnc loop: waiting for: 120

PORT=5900
adb: no devices/emulators found
adb: no devices/emulators found
WARNING. Using fallback path for the emulator registration directory.
emulator: WARNING: System image is writable
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"

adb: device offline
adb: device offline
adb: device offline
adb: device offline
adb: device offline
adb: device offline
adb: device offline
adb: device offline
adb: device offline
adb: device offline
adb: device offline
adb: device offline
```

Am I doing something wrong? Thanks.

**Comment by vania-pooh** [comment]
@bonigarcia startup command did not change since last time. Probably you are trying to launch the same images under incompatible Linux kernel version and because of that emulator is unable to read memory snapshot created by another kernel version. I would recommend rebuilding the image from source code. https://github.com/aerokube/images/blob/master/selenium/automate_android.sh

**Comment by bonigarcia** [comment]
I tried to recreate the image with that [script](https://github.com/aerokube/images/blob/master/selenium/automate_android.sh), using different setups, but no luck. I cannot make it work again.

In any case, it is very inconvenient that the docker images for Chrome Mobile hosted in Docker Hub do not work by default now.

Would it be possible if you to recreate these images (without the snapshot) and upload them to Docker Hub?

**Comment by vania-pooh** [comment]
@bonigarcia without this snapshot session will be starting 30+ seconds.

**Comment by bonigarcia** [comment]
IMO, that delay is better than not working at all.
