### ISSUE TITLE
Problem with version 105 of docker image

### ISSUE THREAD

**Issue by eduardom4020** [aerokube/images#572]
Hi there!

For some reason, when I had downloaded image version 105 in my docker container and try to run it with Webdriver IO, the tools became unable to find the address that I´ve been using for long time, that is http://127.0.0.1:4444. I tryied to run with 0.0.0.0 and localhost too, but nothing worked. Then I reverted image version to 104 and my wdio runned well again.

Best regards!

**Comment by vania-pooh** [comment]
@eduardom4020 need exact commands you are using to start this image.
