### ISSUE TITLE
Add Safari 16 to images

### ISSUE THREAD

**Issue by Rendez** [aerokube/images#576]
The [PR](https://github.com/aerokube/images/pull/463) for Safari 15 is here, but 16 is so far missing. Can someone with more knowledge open a PR for this change?

Thanks community!

**Comment by vania-pooh** [comment]
@Rendez what is exact WebKit version you consider corresponding to Safari 16?

**Comment by Rendez** [comment]
Ok, so I found a resource: https://tauri.app/v1/references/webview-versions/#webkit-versions-in-safari, and I double-checked this along my Safari.app -> `XPCServices/com.apple.WebKit.WebContent.Safari.xpc/Contents/version.plist`

```xml
<key>CFBundleVersion</key>
<string>17614.1.25.9.10</string>
```

Note the `614.1.25.9.10` which seems to be the webkit version, which also is greater than Safari 15 by a couple of major versions, just like it happens between jumps in Safari versions according to that Wikipedia article.

My Safari on the latest Monterey (12.6) at the time of this comment is Version `16.0 (17614.1.25.9.10, 17614)`

**Comment by Rendez** [comment]
For building the docker image I see the build-arg `$WEBKIT_TAG`, but I'm not sure which branch from the webkit repo to pick, e.g.: https://github.com/WebKit/WebKit/tree/safari-7614.1.21-branch

**Comment by Rendez** [comment]
@vania-pooh does this require something else than modifying the .adoc?

**Comment by vania-pooh** [comment]
@Rendez this require building respective image. :)

**Comment by Rendez** [comment]
I tried creating the docker container so far without luck, any hints?

**Comment by vania-pooh** [comment]
@Rendez we are investigating this stuff.

**Comment by aandryashin** [comment]
https://github.com/aerokube/images/tree/master/static/safari
