### ISSUE TITLE
Error 'Operation did not complete successfully because the file contains a virus or potentially unwanted software' while building at windows

### ISSUE THREAD

**Issue by b-r-a-v-o** [aerokube/images#594]
I want build image manually with that steps: https://aerokube.com/images/latest/#_building_procedure

I download repo https://github.com/aerokube/images and run GO commands, but at **go build** command get error:

_go build github.com/aerokube/images: open C:\Users\name\AppData\Local\Temp\go-build2036091527\b001\exe\a.out.exe: Operation did not complete successfully because the file contains a virus or potentially unwanted software._

In windows defender I get critical error:

Threat found: Trojan:Script/Wacatac.B!ml

Is that windows defender error?

**Comment by vania-pooh** [comment]
@b-r-a-v-o I think that's a false positive. You can check source code and make sure we don't have any files like this.
