### ISSUE TITLE
Video recording problem 

### ISSUE THREAD

**Issue by GigiMamaladze** [aerokube/images#600]
I have video’s problem, when test’s work via selenoid i can see everything, but after tests are finished, in video some part’s of test process are missing, for example: opening Passwornd and email page and inputting values. after which in video its already signed in, without this process recorded.  

Here is my browsers.json 

```
{
  "chrome": {
    "default": "100.0",
    "versions": {
      "100.0": {
        "image": "sskorol/selenoid_chromium_vnc:100.0",
        "port": "4444",
        "path": "/",
        "tmpfs": {
          "/tmp": "size=512m"
        }
      }
    }
  }
}
```

Docker-compose.yml

`  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    container_name: "selenoid-compose"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/config/:/etc/selenoid/:ro"
      - "$PWD/config/video:/opt/selenoid/video"
      - "$PWD/config/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/config/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs" ]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: aerokube/selenoid-ui
    container_name: "selenoid-ui-compose"
    network_mode: bridge
    links:
      - selenoid
    hostname: "selenoid.example.com"
    ports:
      - "8090:8080"
    command: [ "--selenoid-uri","http://selenoid:4444" ]
  video-recorder:
    image: selenoid/video-recorder:latest-release
    container_name: "selenoid-video-compose"
    depends_on:
      - selenoid

  chrome:
    image: sskorol/selenoid_chromium_vnc:100.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenoid
    environment:
      - HUB_HOST=selenoid
      - HUB_PORT=4444
      
      `

**Comment by vania-pooh** [comment]
@GigiMamaladze video recorder container is started right after browser container, so probably the beginning of the test execution can be missing in recorded video. At least you can insert a short sleep before executing the test case to fix this.

**Comment by GigiMamaladze** [comment]
is any other variant to fix it without pause ?

**Comment by vania-pooh** [comment]
@GigiMamaladze usually delay is about 1 second maximum. Make sure your VM or server is not slow.

**Comment by GigiMamaladze** [comment]
Okay, thanks
