### ISSUE TITLE
Images build fails:  main.go:7: running "pkger": exit status 1

### ISSUE THREAD

**Issue by vikmaksymenko** [aerokube/images#611]
I'm trying to build custom browser images. I follow the instructions from https://aerokube.com/images/latest/#_building_procedure 

1. Created a file `build.sh` with the following content: 
```bash
set -x
go install github.com/markbates/pkger/cmd/pkger@latest
go generate github.com/aerokube/images
go build
./images --help
set +x
```
2. Run golang container from the `images` repo
`docker run -it -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:1.20 bash build.sh`

Got: 

```
2023/03/10 09:02:43 stat : no such file or directory
main.go:7: running "pkger": exit status 1
+ go build
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
```
Full log in [out.txt](https://github.com/aerokube/images/files/10940422/out.txt)

**Comment by merinsTDL** [comment]
Hi! 
I had a similar issue to build with GG v1.20. This requires to set go path for go packages (i.e. pkger) to find them. 
You can check if path is set by first running pkger command. 
https://stackoverflow.com/questions/21001387/how-do-i-set-the-gopath-environment-variable-on-ubuntu-what-file-must-i-edit
