### ISSUE TITLE
browser/edge 115 and higher

### ISSUE THREAD

**Issue by StanislavKharchenko** [aerokube/images#642]
Good day!
The current edge version is 117
However, image browsers/egde has v114 tagged as latest and last update time was4 months ago.
Do you have plans to update according to most recent msedge ver?

**Comment by vania-pooh** [comment]
@StanislavKharchenko respective webdriver is broken https://github.com/MicrosoftEdge/EdgeWebDriver/issues/102.

**Comment by StanislavKharchenko** [comment]
Thank you!

**Comment by Goraved** [comment]
There is a rumor (In the comments of the EdgeWebDriver issue ) that the issue was solved in Edge 119, which is an actual version for now.

**Comment by vania-pooh** [comment]
@Goraved yes, 119.0 seems to work.

**Comment by Goraved** [comment]
So, are we going to see the new Edge image soon? :)

**Comment by vania-pooh** [comment]
@Goraved yeah, will do.
