### ISSUE TITLE
How quickly can you build & push lastest stable Chrome version Image that supports the new version to DockerHub

### ISSUE THREAD

**Issue by linjin-harvey** [aerokube/images#661]
Hi @vania-pooh 
According to 120 version experience, seems it take weeks for Aerokube to build & push lastest stable version chrome image to docker hub, is it able to build & push the lastest image within 5 days?

I tried to build the lastest stable version chrome image and failed, that's why I'm asking for official support to push lastest image

**Comment by vania-pooh** [comment]
@linjin-harvey source code for our images is open. You can always build images yourself. https://aerokube.com/images/latest/#_building_images
