### ISSUE TITLE
Video file has 0 Bytes when screen resolution has odd numbers

### ISSUE THREAD

**Issue by martingrossmann** [aerokube/images#675]
There seems to be an issue with the used MPEG encoder when the screen resolution of the browser container is set to a dimension with odd numbers like "1000x**801**" or "**1001**x800".

The browser container and VNC are not affected, just the generated video file has a size of 0 Bytes.

I know the workaround is simple and the normal desktop resolutions contains even numbers. But we found that using portrait resolutions to test responsive design. For example Chrome has some predefined resolutions in it's DevTools to simulate other (mobile) devices which contains odd numbers.

**Comment by martingrossmann** [comment]
Thank you for your answer... But it seems the fix was never released? It is from Feb 2012, but the latest `selenoid/video-recorder:latest-release` is from 2020-12-06.

**Comment by martingrossmann** [comment]
Ok, I doublechecked that... The latest Docker Hub image is `sha256:b855ce71aeda6df96c8895cc9cabdb7e70275b2951e56b6b460439db0354ef18` and this was created 2020-12-06, some weeks before your fix.
It seems Docker Hub needs an update?

**Comment by vania-pooh** [comment]
Yeah, probably need to rebuild from source.
