### ISSUE TITLE
VNC no longer connecting in Selenoid UI after vnc_firefox:104.0

### ISSUE THREAD

**Issue by nordicmachine** [aerokube/images#683]
Apologies if this should be in the selenoid-ui project rather than here, but I figured since my setup works up to Firefox 104.0 and breaks at Firefox 105.0 that it might be image related.  

I can view a VNC session in Selenoid UI with Firefox up to version 104.0 but if I try to use any version of Firefox 105.0 and up, it fails.  In Selenoid UI it just says "VNC Connecting" but never actually connects.   I'm using the selenoid vnc_firefox images with the following versions: 

OS:  Red Hat Enterprise Linux release 9.4 (Plow)
Docker CE: Docker version 25.0.3, build 4debf41
Selenoid Version:  Git Revision: 1.11.2 / UTC Build Time: 2024-01-25_02:58:52PM
Selenoid-UI Version: Git Revision: 1.10.11 / UTC Build Time: 2024-01-07_01:38:20PM

I'm running the go binaries directly on the system.  There's no reverse proxies, I'm just connecting directly to selenoid / selenoid-ui.  

I differed the images repoistory between Firefox 104.0 and 105.0 but nothing jumped out at me.  I'm trying to figure out what might be different and causing this issue.  Any help/suggestions would be greatly appreciated.

**Comment by vania-pooh** [comment]
@nordicmachine most probably this is because of SELinux or other RedHat security rescrictions.

**Comment by nordicmachine** [comment]
SELinux is set to Permissive on those hosts.  Would welcome any other thoughts/ideas on how to debug this further.

**Comment by vania-pooh** [comment]
@nordicmachine check what's happening on the developer tools Network tab while you are opening a VNC session. Also are there any errors in Console?
