### ISSUE TITLE
selenoid/firefox images are not pushed for latest version from last 6 months

### ISSUE THREAD

**Issue by aaggarwal-sumo** [aerokube/images#691]
selenoid/firefox images are not pushed for latest version from last 6 months

Latest 131 firefox version is released but in selenoid/firefox we still have till 125 and no new version is getting pushed from last 6 months.

**Comment by konflic** [comment]
Any updates?

**Comment by konflic** [comment]
> selenoid/firefox images are not pushed for latest version from last 6 months
> 
> Latest 131 firefox version is released but in selenoid/firefox we still have till 125 and no new version is getting pushed from last 6 months.

 Now here https://quay.io/repository/browser/google-chrome-stable?tab=tags

**Comment by aaggarwal-sumo** [comment]
For Firefox where I can get from?

**Comment by martingrossmann** [comment]
What does it mean that newer images were not pushed to Docker Hub?

@konflic What kind of images are in that repo?
